name: Block Merge

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  always_fail:
    runs-on: ubuntu-latest
    steps:
      - name: Fail the job
        if: github.event_name == 'merge_group'
        run: exit 1
