name: Merge queue

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  merge-group-check:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Fail the job to prevent merge queue merge
        if: github.event_name == 'merge_group'
        run: exit 1
