name: Merge queue

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  merge-group-check:
    runs-on: ubuntu-latest
    steps:
      - name: Fast forward branch
        if: github.event_name == 'merge_group'
        uses: sequoia-pgp/fast-forward@ea7628bedcb0b0b96e94383ada458d812fca4979
        with:
          merge: true
          github_token: ${{ secrets.VIPVAP_TOKEN }}
      - name: Fail the job to prevent merge queue merge
        if: github.event_name == 'merge_group'
        run: exit 1
