name: Merge queue

on:
  pull_request:
  merge_group:
    types: [checks_requested]

jobs:
  merge-group-check:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR number
        id: pr-number
        run: >-
          echo "pr-number=$(echo '${{ toJson(github) }}' | jq '.event.merge_group.head_ref | capture("refs/heads/gh-readonly-queue/(?<branch>.*)/pr-(?<pr-number>\\d+)-[0-9a-f]{40}") | .pr-number')" | tee -a "${GITHUB_OUTPUT}"
          
      - name: Fail the job to prevent merge queue merge
        if: github.event_name == 'merge_group'
        run: exit 1

      - name: Comment to merge using workflow
        if: ${{ always() }}
        run: >-
          gh pr comment ${{ steps.pr-number.outputs.pr-number }} -R ${{ github.repository }} -b "/fast-forward"
