name: Fast forward merge
on:
  pull_request:
    types: [labeled]

jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: >-
      ${{
        contains(github.event.label.name, 'fast-forward')
      }}
    runs-on: ubuntu-latest

    steps:
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@ea7628bedcb0b0b96e94383ada458d812fca4979
        # See https://docs.github.com/en/graphql/reference/enums#mergestatestatus
        if: ${{ github.event.pull_request.mergeable_state  == 'clean' }}
        with:
          merge: true
          comment: never
          github_token: ${{ secrets.JC_TOKEN }}
