name: Fast forward merge
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: >-
      ${{
        contains(github.event.comment.body, '/fast-forward')
        && github.event.issue.pull_request
      }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Fetch PR state
        id: pr-state
        run: >-
          echo "mergable=$(gh api /repos/${{ env.GITHUB_REPOSITORY }}/pulls/${{ github.event.issue.number }})" | tee -a "${GITHUB_OUTPUT}"

      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@ea7628bedcb0b0b96e94383ada458d812fca4979
        if: ${{ steps.pr-state.outputs.mergeable == 'true' }}
        with:
          merge: true
          comment: on-error
          github_token: ${{ secrets.JC_TOKEN }}
