name: Fast-Forward in merge queue

on:
  merge_group:
    branches:
      - main

jobs:
  fail:
    runs-on: ubuntu-22.04
    steps:
      - name: Fail the job to ensure we only merge using fast forwards
        run: exit 1
